apiVersion: v1
kind: Service
metadata:
  name: freqtrade-dry-run-service
spec:
  type: NodePort
  selector:
    app: freqtrade-dry-run
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # Optional: specify a node port; otherwise, a random port is assigned
